spring:
  application:
    name: data-processor
  data:
    mongodb:
      uri: ${MONGO_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
