version: '3'
services:
  data-generator:
    build:
      context: ./data-generator
    environment:
      - KAFKA_BROKERS=kafka-broker:9092
    networks:
      - emil-network
    depends_on:
      - kafka-broker

  data-processor:
    build:
      context: ./data-processor
    environment:
      - KAFKA_BROKERS=kafka-broker:9092
      - MONGO_URI=mongodb://mongo-service:27017/processed_data
    networks:
      - emil-network
    depends_on:
      - kafka-broker
      - mongo-service
  web:
    build:
      context: ./web
    environment:
      - MONGO_URI=mongodb://mongo-service:27017/processed_data
    networks:
      - emil-network
    depends_on:
      - mongo-service
    ports:
      - "8080:8080"

  kafka-broker:
    image: johnnypark/kafka-zookeeper
    environment:
      - ADVERTISED_HOST=kafka-broker
      - NUM_PARTITIONS=10
    networks:
      - emil-network

  mongo-service:
    image: mongo
    networks:
      - emil-network

networks:
  emil-network:
    driver: "bridge"

